name: Hugging Face 保活

# 每 30 分钟触发一次（可自定义）
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # 手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Check HF Space URL
        run: |
          if [ -z "${{ secrets.HF_SPACE_URL }}" ]; then
            echo "❌ HF_SPACE_URL 未设置，请在仓库 Secrets 中添加"
            exit 1
          fi

      - name: Ping Hugging Face Space
        run: |
          URL="${{ secrets.HF_SPACE_URL }}"
          MAX_RETRIES=3          # 最大重试次数
          RETRY_INTERVAL=10      # 每次重试间隔（秒）
          ATTEMPT=0

          while [ $ATTEMPT -lt $MAX_RETRIES ]; do
            ATTEMPT=$((ATTEMPT + 1))
            echo "⏱ $(date) - 尝试 #$ATTEMPT 访问 $URL"
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$URL" || echo "000")
            
            if [ "$STATUS" = "200" ]; then
              echo "✅ 成功访问 Hugging Face Space (HTTP $STATUS)"
              break
            else
              echo "⚠️ 访问失败 (HTTP $STATUS)"
              if [ $ATTEMPT -lt $MAX_RETRIES ]; then
                echo "⏳ 等待 $RETRY_INTERVAL 秒后重试..."
                sleep $RETRY_INTERVAL
              else
                echo "❌ 所有尝试失败！"
                # 如果你想让 job 失败，可以取消下面注释
                # exit 1
              fi
            fi
          done
